### ISSUE TITLE
Matching Sampleが動作しなくなった

### ISSUE THREAD

**Issue by kou-yeung** [unip2p/UniP2P#2]
MatchingシーンでPlayすると
エラー　[SimpleMatchingClient] GetStatusAsync StatusCode:404　が出力されます。

前回公開したリポジトリでは
MatchingSettingsに マッチングサーバの情報が設定されていますが、
現在は空欄になってます。

**Comment by chujohiroto** [comment]
前回マッチングサーバーの情報が入っていたのは、偶然デバック用のが混入してしまったためです。
本来はマッチングサーバーを自前で建てる必要があります。
こちらを参照してください。

https://qiita.com/ChujoHiroto/items/8f09d65add2d521204c2

**Comment by kou-yeung** [comment]
ありがとうございます。
